version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
